### ISSUE TITLE
Cannot configure sys-apps/nix: librapidcheck is not found.

### ISSUE THREAD

**Issue by LemonBreezes** [trofi/nix-guix-gentoo#36] opened 2023-05-10 14:13 UTC
Getting `configure: error: librapidcheck is not found.` when building `sys-apps/nix` even though I have `dev-cpp/rapidcheck-0_pre20230416::nix-guix` installed. 

The full `emerge` output is here: https://0x0.st/HZhT.txt.

**Comment by trofi** [comment] 2023-05-10 14:57
Looks unexpected.

```
checking for rapidcheck/gtest.h... no
configure: error: librapidcheck is not found.
...
!!! Please attach the following file when seeking support:
!!! /var/tmp/portage/sys-apps/nix-2.15.0/work/nix-2.15.0/config.log
```

Can you extract and attach `config.log` from the path above? I hope it will tell us why `rapidcheck/gtest.h` did not look good enough for `./configure`.

**Comment by LemonBreezes** [comment] 2023-05-10 15:21
> Looks unexpected.
> 
> ```
> checking for rapidcheck/gtest.h... no
> configure: error: librapidcheck is not found.
> ...
> !!! Please attach the following file when seeking support:
> !!! /var/tmp/portage/sys-apps/nix-2.15.0/work/nix-2.15.0/config.log
> ```
> 
> Can you extract and attach `config.log` from the path above? I hope it will tell us why `rapidcheck/gtest.h` did not look good enough for `./configure`.

Sure. These are the contents of  `config.log`: https://0x0.st/HZFO.txt.

**Comment by trofi** [comment] 2023-05-10 16:23
Aha, here is the problematic line:

```
configure:7589: x86_64-pc-linux-gnu-g++ -o conftest -I    -I/usr/include/libcpuid         -I/usr/include -march=native -Ofast -pipe -falign-functions=32 -fno-stack-protector -fpermissive  -L/usr/lib64 -Wl,--as-needed -Wl,-Ofast -Wl,--sort-common conftest.cpp -lrapidcheck -lgtest  >&5
conftest.cpp:36:16: fatal error: rapidcheck/gtest.h: No such file or directory
   36 |       #include <rapidcheck/gtest.h>
      |                ^~~~~~~~~~~~~~~~~~~~
```

Here I would expect the include path being present injected by `export CXXFLAGS="${CXXFLAGS} -I${EPREFIX}/usr/include/rapidcheck/extras/gtest/include"`. But for some reason you don't have anything there.

Let's check what your `environment` file looks like. It should be in `/var/tmp/portage/sys-apps/nix-2.15.0/temp/environment`. Can you attach that one as well?

**Comment by LemonBreezes** [comment] 2023-05-10 19:11
> Aha, here is the problematic line:
> 
> ```
> configure:7589: x86_64-pc-linux-gnu-g++ -o conftest -I    -I/usr/include/libcpuid         -I/usr/include -march=native -Ofast -pipe -falign-functions=32 -fno-stack-protector -fpermissive  -L/usr/lib64 -Wl,--as-needed -Wl,-Ofast -Wl,--sort-common conftest.cpp -lrapidcheck -lgtest  >&5
> conftest.cpp:36:16: fatal error: rapidcheck/gtest.h: No such file or directory
>    36 |       #include <rapidcheck/gtest.h>
>       |                ^~~~~~~~~~~~~~~~~~~~
> ```
> 
> Here I would expect the include path being present injected by `export CXXFLAGS="${CXXFLAGS} -I${EPREFIX}/usr/include/rapidcheck/extras/gtest/include"`. But for some reason you don't have anything there.
> 
> Let's check what your `environment` file looks like. It should be in `/var/tmp/portage/sys-apps/nix-2.15.0/temp/environment`. Can you attach that one as well?

Sure. https://0x0.st/HNrt.txt.

**Comment by trofi** [comment] 2023-05-10 21:39
Your `environment` file does contain expected `declare -x CXXFLAGS="-march=native -Ofast -pipe -falign-functions=32 -fno-stack-protector -fpermissive -I/usr/include/rapidcheck/extras/gtest/include"` flag.

I wonder what manages to filter `-I...` flags out we see in `config.log`: `CXXFLAGS='-I    -I/usr/include/libcpuid         -I/usr/include -march=native -Ofast -pipe -falign-functions=32 -fno-stack-protector -fpermissive'`

I see you have the infrastructure around `FlagReplaceAllFlags`. Can you disable that and see if it is able to retain `CXXFLAGS`? I suspect it has a bug of dropping include paths flags.

**Comment by trofi** [comment] 2023-05-11 07:37
I'm also very confused: your `build.log` contains ` * CXXFLAGS='-march=native -Ofast -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -fuse-linker-plugin -falign-functions=32 -pipe -fno-stack-protector -Wl,-Ofast -Wl,--sort-common -Wl,--as-needed'`. But `config.log` has things like `-fpermissive`. Do you know where discrepancy comes from?

**Comment by trofi** [comment] 2023-05-11 11:46
I tried to rebuild the chroot with the following confgiguration and did not manage to reproduce failure you see:

```
COMMON_FLAGS="-march=native -Ofast -pipe -falign-functions=32 -fno-stack-protector"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

ACCEPT_KEYWORDS="~$ARCH"

FEATURES="${FEATURES} ccache"

NTHREADS="16"

source /etc/portage/make.conf.lto

CFLAGS="-march=native ${CFLAGS} -pipe -falign-functions=32"
CXXFLAGS="${CFLAGS}"
LDFLAGS="-Wl,--as-needed -Wl,-Ofast -Wl,--sort-common"
```

**Comment by trofi** [comment] 2023-05-11 11:48
You might have to debug yourself why `CXXFLAGS` is missing the assignment from `src_prepare()` in `nix` ebuild.

One of the heavy hammers is to run `emerge --debug nix` and attach the build. Maybe we'll see where your execution differs from mine.

**Comment by LemonBreezes** [comment] 2023-05-11 19:00
> You might have to debug yourself why `CXXFLAGS` is missing the assignment from `src_prepare()` in `nix` ebuild.
> 
> One of the heavy hammers you can do is to run `emerge --debug nix` and attach the build.log. Maybe we'll see where your execution differs from mine.

Wow. I don't even know what happened but somehow I tried the installation again today and it worked. I have not even installed anything since then. I'm on WSL2.

**Comment by trofi** [comment] 2023-05-11 20:52
Could it be that you rebuilt a few packages since you tried last time? My primary suspect is `bash`. `$ qlop -muv` might show the recent package changes.

In the past it was known to expose `gcc` bugs like https://gcc.gnu.org/PR88936 (this specific one was fixed in `gcc-9+`, but the problems of the sort might still lurk or resurface there).

**Comment by LemonBreezes** [comment] 2023-05-11 22:28
> Could it be that you rebuilt a few packages since you tried last time? My primary suspect is `bash`. `$ qlop -muv` might show the recent package changes.
> 
> In the past it was known to expose `gcc` bugs like [gcc.gnu.org/PR88936](https://gcc.gnu.org/PR88936) (this specific one was fixed in `gcc-9+`, but the problems of the sort might still lurk or resurface there).

I don't think so actually but here is the output of `qlop -muv`: https://0x0.st/HNPS.txt. I tried installing Nix yesterday (05/10/23) in the morning.

**Comment by trofi** [comment] 2023-05-12 06:33
Yeah, no package reinstalls. So odd.

I wonder if it's a non-deterministic failure. If you try  to build `nix` a few times in sequence, does it succeed all of them? Or happens to fail sometimes?

**Closed as completed** 2023-05-19 08:22 UTC
